//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UseHero1Wrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UseHero1), typeof(System.Object));
		L.RegFunction("PlayHero", PlayHero);
		L.RegFunction("New", _CreateUseHero1);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("_mainView", get__mainView, set__mainView);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUseHero1(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UseHero1 obj = new UseHero1();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UseHero1.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayHero(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			UseHero1.PlayHero();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__mainView(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UseHero1._mainView);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__mainView(IntPtr L)
	{
		try
		{
			FairyGUI.GComponent arg0 = (FairyGUI.GComponent)ToLua.CheckObject<FairyGUI.GComponent>(L, 2);
			UseHero1._mainView = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

