//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameTimesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GameTimes");
		L.RegVar("first", get_first, set_first);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_first(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, GameTimes.first);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_first(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			GameTimes.first = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

